-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.lazy")
-- require("luasnip").config.set_config({ -- Setting LuaSnip config
--
--   -- Enable autotriggered snippets
--   enable_autosnippets = true,
--
--   -- Use Tab (or some other key if you prefer) to trigger visual selection
--   store_selection_keys = "<Tab>",
-- })
-- require("luasnip.loaders.from_lua").load({ paths = { "~/.config/nvim/LuaSnip" } })
--
-- local lspconfig = require("lspconfig")
-- lspconfig.htmx.setup({})
-- An example nvim-lspconfig capabilities setting
-- local capabilities = require("cmp_nvim_lsp").default_capabilities(vim.lsp.protocol.make_client_capabilities())
--
-- -- Ensure that dynamicRegistration is enabled! This allows the LS to take into account actions like the
-- -- Create Unresolved File code action, resolving completions for unindexed code blocks, ...
-- capabilities.workspace = {
--   didChangeWatchedFiles = {
--     dynamicRegistration = true,
--   },
-- }
--
-- require("lspconfig").markdown_oxide.setup({
--   capabilities = capabilities, -- again, ensure that capabilities.workspace.didChangeWatchedFiles.dynamicRegistration = true
-- })
